server:
  port: 9000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.223.164.57:3306/subsidize_system?characterEncoding=utf-8&serverTimezone=GMT%2B8   # ????????????
    username: root
    password: byfan@170307
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  application:
    name: Subsidizesystem-server

  # ????????
  resources:
    static-locations: classpath:/static/

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


  # spring????jackson?????json???????????
  jackson:
    time-zone: GMT+8    # ????????
    date-format: yyyy-MM-dd HH:mm:ss  # ????????