server:
  port: 9000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.223.164.57:3308/subsidize_system?characterEncoding=utf-8&serverTimezone=GMT%2B8   # 设置时区为东八区北京时间
    username: root
    password: 123456
#    password: byfan@170307
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
  application:
    name: Subsidizesystem-server
  # 上传文件大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  jackson:
    time-zone: GMT+8    # 配置时区，东八区
    date-format: yyyy-MM-dd HH:mm:ss  # 默认返回时间格式

  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/,classpath:/static/verifycode/


# 静态文件地址
staticpath: src/main/resources/static/        # 本地启动项目用
#staticpath: /home/                           # docker打包运行用
imagepath: images/                            # 图片文件夹
verifycodepath: verifycode/                   # 验证码地址
noPicturesYetPath: ${imagepath}暂无图片.png    # 暂无图片地址
allowedfiletypes: .png,.jpg,.jpg              # 支持上传的文件类型